[HOPSWORKS-2014]
logicalclocks/hops-util-py pull request #208
Opened 2020-10-09 11:58 UTC by ErmiasG

2020-10-09 15:03 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/197

2020-10-14 12:21 UTC, tkakantousis requested changes
JIRA title missing from PR

2020-10-14 12:21 UTC, tkakantousis commented on hops/constants.py
> +    JSON_KAFKA_NUM_REPLICAS = "numOfReplicas"
wrong copy paste?

2020-10-14 12:21 UTC, tkakantousis commented on hops/credentials_provider.py
> +    if "IS_HOPS_DRIVER" in os.environ:
Maybe move to constants?

2020-11-02 14:27 UTC, tkakantousis approved these changes

2020-11-03 11:25 UTC, merged